### ISSUE TITLE
Rendu final : Livrables

### ISSUE THREAD

**Issue by dosseggegw1** [HEIGVD-PRO-A-07/HEIGVD-PRO-A-07-Documentation#10]
- [ ] Package de test/installation (rapport 2 pages + logiciel client) - voir #11 
- [ ] Démo du logiciel vidéo (5') - voir #12 
- [ ] Docs prévues dans le cahier des charges (archives zip) - voir #13 
- [ ] Organisation du code (rapport 2 pages) - voir #14 
- [ ] Suivi qualité (rapport de 2 pages) - voir #15

**Comment by g-roch** [comment]
Move to HEIGVD-PRO-A-07/HEIGVD-PRO-A-07#83
